name: scx-scheds
on:
  push:
    branches: [main]
    paths: ['scx-scheds/**', 'oci/**', '.github/workflows/scx-scheds.yml', '.github/workflows/_package-image.yml', 'toolchain.env']
  workflow_dispatch:
permissions:
  contents: read
  packages: write
  id-token: write
jobs:
  build:
    uses: ./.github/workflows/_package-image.yml
    secrets: inherit
    with:
      package: scx-scheds
